### ISSUE TITLE
30. 7.

### ISSUE THREAD

**Issue by ksjogo** [ksjogo/oxrti#38]
Part1:
- [x] Indication for Converter, show metadata
- [x] Upload zip file in Viewer
- [x] Metadata display
- [x] Export Manifest

Part2:
- [x] Fix Rotation
- [x] Light: Pointsource
- [x] Hemispherical with Radius
- [x] Fix texture loader speed

Part3:
- [ ] Add RGB format

**Comment by Fleiz-Eiz** [comment]
Im in the Common Room at CS.
